### PR TITLE
Add README.md to point to htslib

### PR DESCRIPTION
**Pull request by jkbonfield**
See https://github.com/jkbonfield/tabix/blob/README/README.md for formatted text.

### CODE REVIEW

**Comment by jkbonfield** [comment]
The only downside with the above statement is it implies the Python / Perl code isn't deprecated.  It is, but it's the only copy of this code.

Would it be better to simply state "This project is deprecated and we do not advise its use" and gloss over the fact it's the sole source for python / perl bindings?  It may encourage those that depend on such things to pull it inhouse and support it themselves (what minimal it needs) as we clearly don't have a need for it.

**Comment by jmarshall** [comment]
This repository contains a bunch of different things:

* _bgzip.c_, _main.c_ (i.e., tabix), and _tabix.1_, which have been superseded for years and actively conflict with the updated editions in HTSlib.

* The other C code, used in building these outdated `bgzip` and `tabix` utilities but also used in building the Perl and Python bindings.

* Python binding: It turns out @slowkow has forked this to [slowkow/pytabix](https://github.com/slowkow/pytabix), which has seen some further maintenance and whence it is built for pypi and Bioconda.

* _tabix.py_, an implementation of `tabix` in Python using the binding in _python/_. This is probably of historical interest only.

* Perl binding: It's unclear whether there's a direct lineage, but this code is surely superseded by Bio::DB::HTS's tabix capabilities  — see [Bio-DB-HTS/lib/Bio/DB/HTS/Tabix.pm](https://github.com/Ensembl/Bio-DB-HTS/blob/master/lib/Bio/DB/HTS/Tabix.pm) etc. OTOH some people may be using this as a lighter-weight Perl module, and there is no obvious other edition of this code elsewhere — though it's certainly unmaintained here.

* Java implementation in _TabixReader.java_: this has been massively improved within HTSJDK — see [htsjdk/…/tribble/readers/TabixReader.java](https://github.com/samtools/htsjdk/blob/master/src/main/java/htsjdk/tribble/readers/TabixReader.java).

* The _tabix.tex_ specification, which has of course moved to hts-specs.

So in fact the only item in this repository for which there is not an obviously better version of the same thing elsewhere to point to is the Perl binding (and hence also the “other C code”).

Packaging-wise, both Debian and SUSE produce packages named tabix, but happily they're built from htslib. (I kind of wish they'd call them htslib-utils or similar ([deb bug 922860](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=922860)) but whatevs.) Bioconda OTOH produces tabix/0.2.5 and tabix/0.2.6 packages (but no “current” package) from the ancient tags on the Sourceforge project corresponding to this repo, which causes some trouble for them — see bioconda/bioconda-recipes#23404.

Things that could be done to signal that all this code is outdated and unmaintained include:

1. Mention it in the repository description — this was done years ago.

2. Add a commit that deletes the files which have better versions elsewhere:  _bgzip.c_, _main.c_, and _tabix.1_; _tabix.tex_; _TabixReader.java_; perhaps _python/*_ but note that it's also used by _tabix.py_.

3. Add a README as per this PR, but expand it to also point to the improved versions of the other items in slowkow/pytabix, Bio::DB::HTS, HTSJDK, and maybe his-specs.

4. Mark the repository as [archived](https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/about-archiving-repositories).

I'd suggest doing 3 and 4, and perhaps 2 apart from _python/*_. Thanks for getting the ball rolling, James.

**Comment by jmarshall** [comment]
It would also be possible to modify the Perl and Python bindings here to build against htslib instead of this _libtabix.*_ or “other C code”, but it would also be mostly pointless as the functionality is superseded by Bio-DB-HTS & pysam and/or that is slowkow/pytabix's concern.

So there's little motivation to make those modifications and it's better to signal that these are unmaintained here.

**Comment by jkbonfield** [comment]
So in summary, the shorter "This project is deprecated and we do not advise its use" is bang on basically.

Agreed there's no point in modifying the perl/python bindings as that is, actually, supporting this project which I think we have no intention of doing given others have already picked up the ball and done better things with it.

The only cases I know of this repository being used is Conda, and that doesn't bundle anything other than bgzip and tabix, so it's totally redundant for them.    Hence why I mentioned the C code in the README and was deliberately obtuse about the other stuff. ;-).  However as you've done the legwork we may as well mention the alternatives too.

**Comment by jmarshall** [comment]
I took the liberty of updating the text to point at the other items too. How does that look, and is there anything else before we start hammering on that final nail?

**Comment by jmarshall** [comment]
On the anniversary of this PR — Is there anything else that should be done before this is merged and the repository is then archived?

**Comment by jkbonfield** [comment]
I'd totally forgotten about it.  I don't know who is responsible for merging.  We're about to start a samtools meeting so will prod. :)

**Comment by daviesrob** [comment]
Merged, at last...

**Comment by jmarshall** [comment]
Huzzah! Do you want to archive the repository as well (in the [repo settings](https://github.com/samtools/tabix/settings) danger zone)? I think it'd be fine to leave the outstanding issues and PRs as is for posterity, though #33 and perhaps #1 should be (answered and) closed first.

**Pull request merged**
